open-runtimes/executor

app/http.php, composer.lock
I was able to confirm memory leak. With our existing recursive loop and 1ms delay between loops, I was able to see linear increase in memory usage from 24MB to 34MB in 30 seconds (no garbage collection visible in 5 mins test). In real-scenario it would take days/weeks until it used hunderds of MBs of memory, but still, worth fixing.
With new logic even with 1ms delay (same setup as above), memory usage was always around 10MB - didn't go high within 5 mins test.
=> Fix: memory leak in recursion

app/http.php, tests/ExecutorTest.php
`outputSize` integer added to response of createRuntime. (when used as build server)
=> Feat: Add build size to response

app/http.php
=> Feat: Improve logs

app/http.php
=> Feat: Improve logging label

app/http.php
Pool size 30 is not able to pull all images during startup
=> Fix: Set pool size to 100

composer.lock
Upgrade runtimes lib version to introduce 3.1 support for Dart (pre-fetch images)
=> Feat: Dart 3.1

composer.json, composer.lock
Upgrading Storage fixes issue with symlink deletion. Addressing following problem:
=> Feat: Upgrade storage lib

composer.lock
Upgrades lib, adds support for python 3.12, if used in env var to auto-pull image.
Related PR:
https://github.com/open-runtimes/open-runtimes/pull/211
Tests:
None
=> Feat: Python 3.12 auto-pull image

Dockerfile
=> Feat: Docker healthcheck

app/http.php
The code is no longer needed, and always succeeds on first retry. This is thanks to cold-start TCP ping right before that.
=> Fix: Remove deprecated retry loop

app/http.php, src/Executor/Validator/TCP.php
this PR fixes those 2 warnings:
=> Fix: listening state

README.md, app/http.php, composer.json, composer.lock
- Combine both logger fields into one
- Adjusted to the latest Utopia logger library
=> Unified Config logger 

composer.json, composer.lock
Upgrade lib to support Go runtime
=> Chores: Go support

app/http.php
Logic no longer needed, logs&errors are no longer headers
=> Chore: remove leftover

app/http.php, composer.json, composer.lock
=> fix: improve build error

app/http.php
Copy&paste resource from Proxy. It was manually QA in Proxy PR here: https://github.com/open-runtimes/proxy/pull/33
=> Fix: host issues

app/http.php
Sites dont have entrypoint. It should no longer be required
=> Fix: cold start for sites

.github/workflows/codeql-analysis.yml, app/http.php, composer.json, composer.lock
=> Fix: Orchestration stats

composer.json, composer.lock
Adds support for a few new runtimes
=> Chore: upgrade runtime libs

app/http.php
=> Fix: logging race condition

src/Executor/Runner/Docker.php
(not nessessary in v5 anymore)
=> Fix: Remove lockfile
