app/http.php
tests/ExecutorTest.php

Coldstart time was ignored in execution duration.
Now it is added for proper duration tracking.

Fix: coldstart duration calculation

---

app/http.php

We previously only deleted files, resulting in empty folders in `/tmp`. Now we remove the whole folder.

Fix: Temp runtime dir cleanup

---

app/http.php

There are 2 possible race conditions that would result in Docker CLI error - duplicate container name.
1. Retrying failed build too quickly
2. Starting 2 builds of same name at the same time
This PR solves both.

Fix: Build race condition

---

app/http.php
tests/ExecutorTest.php
tests/resources/functions/node-empty-array/index.js
tests/resources/functions/node-empty-object/index.js
tests/resources/functions/node-stderr/index.js

With successful execution, stderr was ignored. Now both stdout and stderr are ALWAYS present, as intended.
+ I noticed small bug when empty object is translated to empty array. Fixed that.
I also improved maintainability of tests a little to prevent code duplication.
With that I added tests for some more edge cases: stderr, json object response.

Fix: stderr response

---

app/http.php

Files above 134MB cannot be built with error:
```
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 267720208 bytes) in /usr/local/vendor/utopia-php/storage/src/Storage/Device/Local.php on line 271
```
By using transfer method, upload & read should be done in chunks to prevent this problem.

Feat: chunk storage read/writes

---

app/http.php

Quick fix of a bug when using different device than local.
Nessessary before using latest version of Executor with Appwrite 1.4, otherwise all builds with cloud storage provider fails.

Fix: Remote storage

---

app/http.php

Related asana task: https://app.asana.com/0/1201750942661288/1205748750268399/f

Remove unique identifiers from runtime error title

---

app/http.php

$orchestration->run() sometimes also returns additional information such as output from pulling docker images. As such, it's not reliable to use the output for the container ID. Instead, we can just use the container name for operations on the container.
Since we won't use the container ID, we can remove the 'id' column from the activeRuntimes table.
Relates:
* https://github.com/appwrite/appwrite/issues/6362

Fix docker conflict error

---

app/http.php
tests/ExecutorTest.php

The runtimeId will be the ID passed into the executor. From there, the runtimeName will be the hostname + runtimeId. We want to prefix with hostname to support multiple executors on the same machine.
The runtimeName will be used for the container name and the active runtimes table.
Confirmed building works:
Confirmed executing works:

Clarify active runtime ID usage in the executor

---

app/http.php
tests/ExecutorTest.php

Accept header syntax didnt allow `, `, and `*`. Both now supported properly, and tested.

Fix: accept headers

---

app/http.php

The validation is already done on param level in HTTP request

Fix: Remove double validation

---

README.md
app/http.php
composer.lock

This PR makes CPU's float so they work correctly with variable runtimes

Make CPU's float

---

.github/workflows/tests.yml
composer.json
composer.lock
tests/ExecutorTest.php

I added test that ensures build folders are cleaned up properly.
I also:
- Rewrite tests to not be dependent
- Removed unnecessary swoole configuration (was causing trouble when running non-streamed tests)

Fix: cleanup tests

---

app/http.php

Include runtime image in log report. Helps identify if a problem is runtime-specific, or global (on executor).

Feat: Runtime image logging

---

app/http.php
tests/ExecutorTest.php
tests/resources/functions/node-specs/build.js
tests/resources/functions/node-specs/index.js
tests/resources/functions/node-specs/package.json

Feat: Specifications OPR env var

---

app/http.php
tests/ExecutorTest.php

When you make a request to create an execution, and the runtime doesn't exist yet, the executor tries to create the runtime first. If the runtime is already being created by another request (and exists in the `activeRuntimes` table with a 'pending' status), the /v1/runtimes endpoint returns a 409 Conflict error with the message:
```
A runtime with the same ID is already being created. Attempt a execution soon.
```
In the execution creation code, specifically in the loop that attempts to create the runtime, any HTTP response with a status code between 400 and 499 (inclusive) is treated as a fatal error, and it immediately throws an exception instead of retrying. This means that when the executor receives a 409 status code, it doesn't retry and instead exits the loop, leading to this error …

fix: runtime ready loop

---

app/http.php
composer.lock

We also update orchestration lib, preventing health check from saying executor is not running any container when just one has issue getting status

Feat: Deprecate status

---

app/http.php

Reverts: https://github.com/open-runtimes/executor/pull/129
Re-adds status params expected by OPR Proxy version used on production

Fix: Health endpoint compatibility

---

Dockerfile
app/http.php
app/run.php
composer.json
composer.lock
src/Executor/Runner/Adapter.php
src/Executor/Runner/Docker.php
src/Executor/Stats.php

This moves runner related code into an adapter.

Adapter pattern

---

app/controllers.php
composer.json
composer.lock
src/Executor/BodyMultipart.php

- adds CURLFile support to executor to allow multipart uploads (needed inside edge)
- scopes executor authentication to executor apis, required so edge can implement own privileged apis

chore: scope auth to executor

---

tests/ExecutorTest.php

Splits up testErrors so we can opt out of the specific ones that break on Edge without skipping them all

test: split testErrors

---

app/config/errors.php
app/controllers.php
app/error.php
app/init.php
composer.json
composer.lock
src/Executor/Exception.php
src/Executor/Runner/Docker.php
tests/ExecutorTest.php

Refactor exception handling on Executor, inspired by exception handling on Appwrite and Cloud. We need this in order to easily declare new exceptions on Edge, and control when they should be public/logged.
Following the pattern in Appwrite:
- `config/errors.php `contains an array of error details for HTTP responses. Includes `publish` field to solve our recurring visibility issues with errors.
- `Exception.php` defines a HTTP layer exception, automatically populated using the defaults `config/errors.php`
- For now I've focused on 400 level errors, and kept the output of the errors the same, so tests are passing.
This is still not the perfect system, ideally we'd have domain level exceptions (mostly within Docker.php), and they should be caught and rethrown into HTTP layer exceptions (in …

refactor: exceptions

---

src/Executor/Runner/Docker.php
tests/ExecutorTest.php

shifts `deletePath` function call to fix this warning:
`Warning: rmdir(/tmp/executor-test-log-stream-38bf304a/src/logging): Permission denied in /usr/local/vendor/utopia-php/storage/src/Storage/Device/Local.php on line 380`
passes locally

chore: add test for head request

---

app/controllers.php
src/Executor/Runner/Docker.php
tests/Client.php
tests/ExecutorTest.php
tests/resources/functions/php/index.php
tests/resources/sites/astro/src/pages/logs.astro

Reverts breakng changes in 0.9.0, and adds support for multiple cookies in set-cookie
- Assertion in function was passing without main change too, but good to ensure
- Test in Astro cookie was NOT passing without main change
Main change:
https://github.com/open-runtimes/executor/blob/feat-set-cookie-comma-separtion/src/Executor/Runner/Docker.php#L980-L984

Feat: coma-separated set-cookie

---

src/Executor/Runner/Docker.php

Connection should be just warning, in case it's just an "already exists", which can happen easily when running docker-compose and executor is already mentioned as part of network there.

Fix connection warning
